### ISSUE TITLE
[SCOPE] Avoid US centric language

### ISSUE THREAD

**Issue by iadawn** [w3c-cg/aar#31]
More of a general point which I am sure is being considered. However, K-12 is a US term which may be unclear depending on reader location. Age may be a more neural approach or there may be something that is used in international educator speak that I have no knowledge of - could be K-12!!

**Comment by brianelton** [comment]
I agree that we should probably use an age-based approach. I will update.

**Comment by brianelton** [comment]
addressed in #34
